### ISSUE TITLE
Query Returning Empty Results

### ISSUE THREAD

**Issue by gaurav-newzera** [sgottsch/eventkg#5]
Hello, I extracted EventKG .nq files by following the steps mentioned. I loaded them using tdbloader of Apache Jena. But when I am running any query on it, the output is empty. Can you let me know where am I going wrong? One of the example queries which I tried is shown below:

The command used to load files was:
`bin/tdbloader --loc db path_to_output/*.nq`

Here is how I run the query:

```
bin/tdbquery --loc loaded_db/ '
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX eventKG-s: <http://eventKG.l3s.uni-hannover.de/schema/>
PREFIX eventKG-g: <http://eventKG.l3s.uni-hannover.de/graph/>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?locationDBPediaEn ?locationEventKG 
WHERE 
{ 
 ?event rdf:type sem:Event . 
 ?event rdfs:label "Battle of Trafalgar"@en .
 GRAPH eventKG-g:event_kg {?event sem:hasPlace ?locationEventKG} . 
 GRAPH eventKG-g:dbpedia_en { ?locationEventKG owl:sameAs ?locationDBPediaEn . } 
}'
```

The output I get is:

```
---------------------------------------
| locationDBPediaEn | locationEventKG |
=======================================
---------------------------------------
```

**Comment by sgottsch** [comment]
Hi,

The query is working fine on our [public SPARQL endpoint](http://eventkginterface.l3s.uni-hannover.de/sparql?query=SELECT+DISTINCT+%3FlocationDBPediaEn+%3FlocationEventKG+%0D%0AWHERE+%0D%0A%7B+%0D%0A+%3Fevent+rdf%3Atype+sem%3AEvent+.+%0D%0A+%3Fevent+rdfs%3Alabel+%22Battle+of+Trafalgar%22%40en+.%0D%0A+GRAPH+eventKG-g%3Aevent_kg+%7B%3Fevent+sem%3AhasPlace+%3FlocationEventKG%7D+.+%0D%0A+GRAPH+eventKG-g%3Adbpedia_en+%7B+%3FlocationEventKG+owl%3AsameAs+%3FlocationDBPediaEn+.+%7D+%0D%0A%7D&format=text%2Fhtml), so the error it with the extraction of the files.

Can you show me a list of the .nq files you have extracted (plus, if possible, the file size)?

**Comment by gaurav-newzera** [comment]
Here is the list of generated files.

```
(base) gaurav@newzera-MS-7C60:~$ ls -lh eventKG/event_kg_data/output
total 71G
-rw-rw-r-- 1 gaurav gaurav 9.6G Aug 14 08:13 entities.nq
-rw-rw-r-- 1 gaurav gaurav 1.1G Aug 13 14:21 events.nq
-rw-rw-r-- 1 gaurav gaurav 1.9K Aug 13 14:15 graphs.ttl
-rw-rw-r-- 1 gaurav gaurav 170K Aug 13 14:25 property_labels.nq
-rw-rw-r-- 1 gaurav gaurav  12G Aug 14 11:13 relations_base.nq
-rw-rw-r-- 1 gaurav gaurav 8.1G Aug 13 14:25 relations_entities_other.nq
-rw-rw-r-- 1 gaurav gaurav 6.6G Aug 13 14:25 relations_entities_temporal.nq
-rw-rw-r-- 1 gaurav gaurav 6.3G Aug 13 14:40 relations_entity_links.nq
-rw-rw-r-- 1 gaurav gaurav  17G Aug 13 14:40 relations_event_links.nq
-rw-rw-r-- 1 gaurav gaurav 378M Aug 13 14:25 relations_events_literals.nq
-rw-rw-r-- 1 gaurav gaurav 3.7G Aug 13 14:24 relations_events_other.nq
-rw-rw-r-- 1 gaurav gaurav 1.2K Aug 13 14:15 schema.ttl
-rw-rw-r-- 1 gaurav gaurav 121K Aug 13 14:40 type_labels_dbpedia.nq
-rw-rw-r-- 1 gaurav gaurav 6.9M Aug 13 14:48 type_labels_wikidata.nq
-rw-rw-r-- 1 gaurav gaurav 446M Aug 13 14:49 types_dbpedia.nq
-rw-rw-r-- 1 gaurav gaurav 4.1G Aug 13 14:50 types.nq
-rw-rw-r-- 1 gaurav gaurav 267K Aug 13 14:49 types_ontology_dbpedia.nq
-rw-rw-r-- 1 gaurav gaurav 3.1G Aug 13 14:47 types_wikidata.nq
-rw-rw-r-- 1 gaurav gaurav 2.8K Aug 13 14:15 void.ttl
```

The files are same as mentioned [here](http://eventkg.l3s.uni-hannover.de/data.html). I was wondering if it was some issue while I loaded them in the triple stores.

**Comment by gaurav-newzera** [comment]
Here is the list of generated files.

```
(base) gaurav@MS-7C60:~$ ls -lh eventKG/event_kg_data/output
total 71G
-rw-rw-r-- 1 gaurav gaurav 9.6G Aug 14 08:13 entities.nq
-rw-rw-r-- 1 gaurav gaurav 1.1G Aug 13 14:21 events.nq
-rw-rw-r-- 1 gaurav gaurav 1.9K Aug 13 14:15 graphs.ttl
-rw-rw-r-- 1 gaurav gaurav 170K Aug 13 14:25 property_labels.nq
-rw-rw-r-- 1 gaurav gaurav  12G Aug 14 11:13 relations_base.nq
-rw-rw-r-- 1 gaurav gaurav 8.1G Aug 13 14:25 relations_entities_other.nq
-rw-rw-r-- 1 gaurav gaurav 6.6G Aug 13 14:25 relations_entities_temporal.nq
-rw-rw-r-- 1 gaurav gaurav 6.3G Aug 13 14:40 relations_entity_links.nq
-rw-rw-r-- 1 gaurav gaurav  17G Aug 13 14:40 relations_event_links.nq
-rw-rw-r-- 1 gaurav gaurav 378M Aug 13 14:25 relations_events_literals.nq
-rw-rw-r-- 1 gaurav gaurav 3.7G Aug 13 14:24 relations_events_other.nq
-rw-rw-r-- 1 gaurav gaurav 1.2K Aug 13 14:15 schema.ttl
-rw-rw-r-- 1 gaurav gaurav 121K Aug 13 14:40 type_labels_dbpedia.nq
-rw-rw-r-- 1 gaurav gaurav 6.9M Aug 13 14:48 type_labels_wikidata.nq
-rw-rw-r-- 1 gaurav gaurav 446M Aug 13 14:49 types_dbpedia.nq
-rw-rw-r-- 1 gaurav gaurav 4.1G Aug 13 14:50 types.nq
-rw-rw-r-- 1 gaurav gaurav 267K Aug 13 14:49 types_ontology_dbpedia.nq
-rw-rw-r-- 1 gaurav gaurav 3.1G Aug 13 14:47 types_wikidata.nq
-rw-rw-r-- 1 gaurav gaurav 2.8K Aug 13 14:15 void.ttl
```

The files are same as mentioned here. I was wondering if it was some issue while I loaded them in the triple stores.

**Comment by sgottsch** [comment]
I could reproduce your error. And I agree that there is an error when loading the graphs.ttl file with the TDBloader.

There were two problems:
- The EventKG prefix URIs need to be 100% lowercase. It should be "http://eventkg.l3s.uni-hannover.de/resource", not "http://eventKG.l3s.uni-hannover.de/resource"
- Prefixed URIs should not have angular brackets (e.g., use "eventKG-g:yago" instead of "<eventKG-g:yago>")

I have just pushed changes to the DataStoreWriter and the PrefixEnum. You should now be able to create a proper graphs.ttl file (either by just running DataStoreWriter's writeDataSetDescriptions() after initialisation, or by manually changing your graphs.ttl file).

**Comment by gaurav-newzera** [comment]
Thanks for the update. I am able to load the graph.ttl files but because of the presence of "\" in DBpeida's IRI in entities.nq and also at many places in relations_events_literals.nq loading them in Apache Jena is throwing error. I wanted to know if it is fine to replace "\" with "%5C" across all the files (like even when backslash is used as escape character like \\, \" etc)?

**Comment by gaurav-newzera** [comment]
I was able to load the data in Virtuoso and the queries were also executing fine. Thanks for the help.
Suggestion: The .nq files generated are not loading via TDBloader, maybe that's an area of improvement.
